name: Nasa project CI
on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]
jobs:
  build:
    env: 
      CI: true # with IC env, watch mode when test will be disable
      MONGO_URI: mongodb://localhost/nasa
    strategy:
      matrix:
        node-version: [16.x] # will use the latest version of node 14 and 16 to build in parallel 
        mongodb-version: [4.4]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use NodeJS version ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          # node-version: '16'
          node-version: ${{matrix.node-version}}

      - name: Use MongoDB from github actions
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }} 

      - run: npm i
      - run: npm run build --prefix client
      - run: npm test